### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by g-adel** [bramses/youtube-transcript-obsidian#3]
Great plugin! I really think there's plenty of utility for a plugin like this. One feature that I would love to see implemented would be a search bar at the top. It could filter through the quote blocks and just show the matching ones.

**Comment by bramses** [comment]
Thanks @j-maffe! Any reason regular search in file (cmd-f) doesn't work for this case? Or are you thinking something different?

**Comment by g-adel** [comment]
Oh very sorry, I confused your plugin for YTranscript on the store. Yes the issue is meaningless in this context haha
